exec swayidle -w \
    timeout 120 'if grep -q "0" /sys/class/power_supply/*/online 2>/dev/null; then swaymsg "output * power off"; fi' \
    resume 'swaymsg "output * power on"' \
    timeout 600 'if grep -q "0" /sys/class/power_supply/*/online 2>/dev/null; then systemctl suspend; else swaylock -f -i /home/pa3k/Pictures/BingWallpapers/bing-latest.jpg && swaymsg "output * power off"; fi' \
    timeout 18000 'if grep -q "1" /sys/class/power_supply/*/online 2>/dev/null; then systemctl suspend; fi' \
    before-sleep 'swaylock -f -i /home/pa3k/Pictures/BingWallpapers/bing-latest.jpg'
