setw -g mode-keys vi
set -g mouse on

# Update the status bar every x seconds
set -g status-interval 60

#set -g status-right " 1m | (~/scripts/fedora-sway/tmux/tmux-status-bar-stats.sh) | %a %m/%d %H:%M"
set -g status-right " 1m (~/scripts/fedora-sway/tmux/tmux-status-bar-stats.sh #{client_width}) %a %m/%d %H:%M"
set -g status-right-length 150
#set -g status-left "#(~/scripts/fedora-sway/tmux/tmux-status-bar-stats.sh)"
#set -g status-left-length 100

# 2. Push the open windows list to the right side of the screen
#set -g status-justify left

# 3. Keep only the essential clock/user on the far right
#set -g status-right " | %a %m/%d %H:%M"
#set -g status-right-length 50

# ---------------------------------------------------------
# Dynamic Status Interval Toggles
# ---------------------------------------------------------

# Prefix + i : "Performance Mode" (Updates every 2 seconds)
#bind i set -g status-interval 2 \; set -g status-right " 2s | #(~/scripts/fedora-sway/tmux/tmux-status-bar-stats.sh) | %a %m/%d %H:%M" \; display-message "Performance Mode: Status updates every 2s"
bind i set -g status-interval 2 \; set -g status-right " 2s #(~/scripts/fedora-sway/tmux/tmux-status-bar-stats.sh #{client_width}) %a %m/%d %H:%M" \; display-message "Performance Mode: Status updates every 2s"

# Prefix + I (Shift+i) : "Battery Mode" (Updates every 60 seconds)
#bind u set -g status-interval 60 \; set -g status-right " 1m | #(~/scripts/fedora-sway/tmux/tmux-status-bar-stats.sh) | %a %m/%d %H:%M" \; display-message "Battery Mode: Status updates every 60s"
bind u set -g status-interval 60 \; set -g status-right " 1m #(~/scripts/fedora-sway/tmux/tmux-status-bar-stats.sh #{client_width}) %a %m/%d %H:%M" \; display-message "Battery Mode: Status updates every 60s"

# Prefix + u : "Ultra Power Saver" (Updates every 5 minutes / 300 seconds)
#bind U set -g status-interval 300 \; set -g status-right " 5m | #(~/scripts/fedora-sway/tmux/tmux-status-bar-stats.sh) | %a %m/%d %H:%M" \; display-message "Ultra Power Saver: Status updates every 5m"
bind U set -g status-interval 300 \; set -g status-right " 5m #(~/scripts/fedora-sway/tmux/tmux-status-bar-stats.sh #{client_width}) %a %m/%d %H:%M" \; display-message "Ultra Power Saver: Status updates every 5m"
